group=org.jetbrains.plugins.kotlin.jupyter
pluginVersion=2026.2-SNAPSHOT

intellijPlatformVersion=262-EAP-SNAPSHOT

# Kotlin compiler settings
kotlin.stdlib.default.dependency=false

# Gradle build performance
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m

# Gradle version
gradleVersion=9.4.1
