# IntelliJ Platform Artifacts Repositories
# -> https://www.jetbrains.org/intellij/sdk/docs/reference_guide/intellij_artifacts.html

pluginGroup = org.jetbrains.plugins.jupyter.kotlin
pluginName_ = KotlinJupyter
pluginVersion = 0.0.1
pluginSinceBuild = 201
pluginUntilBuild = 211.*

platformType = IU
platformVersion = 2020.2.4
platformDownloadSources = true
platformLocalPath = C:/Users/Ilya.Muradyan/AppData/Local/JetBrains/IntelliJIdea2020.2.4.jupyter

# Plugin Dependencies -> https://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_dependencies.html
# Example: platformPlugins = com.intellij.java,com.jetbrains.php:203.4449.22
# platformPlugins = org.jetbrains.kotlin
intellijBuildNumber = 202.8308

# Opt-out flag for bundling Kotlin standard library.
# See https://kotlinlang.org/docs/reference/using-gradle.html#dependency-on-the-standard-library for details.
kotlin.stdlib.default.dependency = false

kotlinVersion = 1.4.30-dev-3354
ktlintVersion = 9.4.1
notebookApiVersion = 0.8.3.2.dev43
jarjarVersion = 1.2.0
