# IntelliJ Platform Artifacts Repositories
# -> https://www.jetbrains.org/intellij/sdk/docs/reference_guide/intellij_artifacts.html

pluginGroup = org.jetbrains.plugins.jupyter.kotlin
pluginName_ = KotlinJupyter
pluginVersionStub = 0.0.1

intellij.platform.version.main = 212
intellij.platform.version.build = 2372
intellij.kotlin.build = 1.4.32-release

# Prefer archive unpacking over locally installed IDE
intellij.platform.local.prefer.archive = true

# If prefer.archive is true, try to download archive from TeamCity if it was not found locally
intellij.platform.local.archive.download = true

# Local archive path
intellij.platform.local.archive = artifacts/ideaIU-{ijVer}.{ijBuild}.win.zip

# Local IDE path
intellij.platform.local.path.stub =

platformType = IU
platformDownloadSources = true

# Opt-out flag for bundling Kotlin standard library.
# See https://kotlinlang.org/docs/reference/using-gradle.html#dependency-on-the-standard-library for details.
kotlin.stdlib.default.dependency = false

kotlinVersion = 1.5.20-dev-4184
ktlintVersion = 10.0.0
notebookApiVersion = 0.9.0-25
junitVersion = 4.13.2
kotestVersion = 4.4.3
detektVersion = 1.16.0
changelogVersion = 1.1.2

jvmTarget_ = 11
runIdeMaxMemory = 2000m
