[versions]
intellijPlatformPlugin = "2.14.1-SNAPSHOT"
nonBundledMonorepoPlugins = "262.7581.3"
kotlin = "2.3.20"
kotlinxSerializationCore = "1.11.0"
kotlinxCoroutines = "1.10.2"
kotlinJupyter = "0.18.1-907"
letsPlotExportShadowed = "4.7.3-32"
letsPlotKotlinJson = "4.13.0"
jackson = "2.21.2"
slf4j = "2.0.17"
kotest = "5.9.1"
junit4 = "4.13.2"
jvmTarget = "25"
jupyterParser = "0.3.0-100"
clikt = "2.8.0"

[libraries]
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerializationCore" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationCore" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }

kotlin-jupyter-ws-server = { module = "org.jetbrains.kotlinx:kotlin-jupyter-ws-server", version.ref = "kotlinJupyter" }

jupyter-notebook-parser = { module = "org.jetbrains.kotlinx:jupyter-notebooks-parser", version.ref = "jupyterParser" }

lets-plot-export-shadowed = { module = "org.jetbrains.lets-plot:lets-plot-export-shadowed", version.ref = "letsPlotExportShadowed" }
lets-plot-kotlin-json = { module = "org.jetbrains.lets-plot:lets-plot-kotlin-json", version.ref = "letsPlotKotlinJson" }

jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

clikt = { module = "com.github.ajalt:clikt", version.ref = "clikt" }

kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
junit4 = { module = "junit:junit", version.ref = "junit4" }

[plugins]
intellijPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intellijPlatformPlugin" }
intellijPlatformModule = { id = "org.jetbrains.intellij.platform.module" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

# Not real Gradle plugins — IntelliJ Platform marketplace plugin dependencies
nonBundledIntellij-jupyter = { id = "intellij.jupyter", version.ref = "nonBundledMonorepoPlugins" }
nonBundledIntellij-notebooksCore = { id = "com.intellij.notebooks.core", version.ref = "nonBundledMonorepoPlugins" }
