[versions]
intellijPlatform = "262-EAP-SNAPSHOT"
intellijPlatformPlugin = "2.6.0"
kotlin = "2.1.21"
kotlinxSerializationCore = "1.7.3"
kotlinxCoroutines = "1.8.1"
kotlinJupyter = "0.18.1-907"
letsPlot = "4.9.3"
jackson = "2.17.1"
clikt = "2.8.0"
slf4j = "2.0.13"
jvmTarget = "21"

[libraries]
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerializationCore" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationCore" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }

kotlin-jupyter-api = { module = "org.jetbrains.kotlinx:kotlin-jupyter-api", version.ref = "kotlinJupyter" }
kotlin-jupyter-lib = { module = "org.jetbrains.kotlinx:kotlin-jupyter-lib", version.ref = "kotlinJupyter" }
kotlin-jupyter-ws-server = { module = "org.jetbrains.kotlinx:kotlin-jupyter-ws-server", version.ref = "kotlinJupyter" }
kotlin-jupyter-shared-compiler = { module = "org.jetbrains.kotlinx:kotlin-jupyter-shared-compiler", version.ref = "kotlinJupyter" }
kotlin-jupyter-common-dependencies = { module = "org.jetbrains.kotlinx:kotlin-jupyter-common-dependencies", version.ref = "kotlinJupyter" }

lets-plot-export-shadowed = { module = "org.jetbrains.lets-plot:lets-plot-export-shadowed", version.ref = "letsPlot" }
lets-plot-kotlin-json = { module = "org.jetbrains.lets-plot:lets-plot-kotlin-json", version.ref = "letsPlot" }

clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

[plugins]
intellijPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intellijPlatformPlugin" }
intellijPlatformModule = { id = "org.jetbrains.intellij.platform.module", version.ref = "intellijPlatformPlugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
